# Generated by Django 4.1.7 on 2023-04-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0004_department_dept_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('courses', models.ManyToManyField(related_name='students', to='departments.course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.section')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.series')),
            ],
        ),
    ]
