# Generated by Django 4.1.7 on 2023-10-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('students', '0005_studentcourse_unique_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcourse',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='departments.gradepoint'),
        ),
        migrations.AlterField(
            model_name='labcourse',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labcourse',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='departments.gradepoint'),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theorycourse',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
