# Generated by Django 4.1.7 on 2023-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_labcourse_grade_alter_labcourse_obtained_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcourse',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labcourse',
            name='labPerformance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labcourse',
            name='viva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
