# Generated by Django 4.1.7 on 2023-10-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_labcourse_examfor_alter_theorycourse_examfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtest',
            name='full_marks',
            field=models.IntegerField(default=20),
        ),
    ]
