# Generated by Django 4.1.7 on 2023-10-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_courseteacherassignment_teacher'),
        ('students', '0009_alter_classtest_full_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtest',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_tests', to='teachers.teacher'),
        ),
    ]
