# Generated by Django 4.1.7 on 2023-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_theorycourse_sectiona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorycourse',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
