# Generated by Django 4.1.7 on 2023-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_theorycourse_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtest',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
