# Generated by Django 4.1.7 on 2023-10-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_courseteacherassignment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='teachers.teacher'),
        ),
    ]
