# Generated by Django 4.1.7 on 2023-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
