# Generated by Django 4.1.7 on 2023-09-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
