# Generated by Django 4.1.7 on 2023-10-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=10),
        ),
    ]
