# Generated by Django 4.1.7 on 2023-04-14 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=4, unique=True)),
                ('dept_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=10)),
                ('semester', models.IntegerField()),
                ('isAllocated', models.BooleanField(default=False)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('description', models.JSONField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department')),
            ],
        ),
    ]
