# Generated by Django 4.1.7 on 2023-04-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'title']},
        ),
    ]
