# Generated by Django 4.1.7 on 2023-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradepoint',
            name='maximum_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='exam_status',
            field=models.CharField(choices=[('NR', 'Not Running'), ('R', 'Running'), ('F', 'Finished')], default='NR', max_length=10),
        ),
    ]
