# Generated by Django 4.1.7 on 2023-04-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_series_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
