# Generated by Django 4.1.7 on 2023-06-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_name'),
        ('departments', '0004_department_dept_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_head', to='teachers.teacher'),
        ),
    ]
